Trait {
	#name : #CollectableCollectionsManagerServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'Collectable-Core'
}

{ #category : #'services- collectibles' }
CollectableCollectionsManagerServices >> getAllCollectibles [
]

{ #category : #'services - collections' }
CollectableCollectionsManagerServices >> getCollections [
]

{ #category : #'services- collectibles' }
CollectableCollectionsManagerServices >> numberOfCollectibles [
]

{ #category : #'services - collections' }
CollectableCollectionsManagerServices >> setCollections: aCollectionList [
]
